### ISSUE TITLE
Log button reset

### ISSUE THREAD

**Issue by bschulz1701** [NorthernWidget-Skunkworks/Margay_Library#14]
### Issue:
On branch `Dev_v2` commit ade9e0f92979aa52f8432f1ad55c1a049a3c24f9, when using Margay `v1.0` hardware, when the log button is pressed the system resets

### Potential Fix:
Most likely an interrupt vector problem, make sure the vector is setup properly for the pin

**Comment by awickert** [comment]
@bschulz1701 thinks that the vector is just pointing to 0 and resetting.

Won't fix: this is outdated. This isn't a mission-critical problem for a deprecated system. Can fix if there is a great need.
