### ISSUE TITLE
Fix battery voltage measurement 

### ISSUE THREAD

**Issue by bschulz1701** [NorthernWidget-Skunkworks/Margay_Library#4]
Battery voltage is off by a large margin due to the high input impedance of the voltage divider. Find low level work around.

### Solution:
Adjusted the default voltage reference (unsure of what default state is), and set to use **AREF** pin, this was done with `ADMUX = 0b00000000;`, also sets mux to ADC0 for some time before the measurement is made, allowing the sample and hold cap to charge up beforehand. 

Also set clock divider to maximum, again, allowing for the longest sampling interval for the Sample and Hold cap to charge. This was done with `ADCSRA = 0b10000111;`

Finally, measured **VRef** pin (1.8v reference) and used this to compensate for errors in 3.3v reference voltage assumption. Important, this measurement should be made **after** the divided battery voltage measurement, otherwise this defeats the precharge we performed.

Note: Hardware solution would be to use a lower value voltage divider, or use a unity gain buffer on the input stage of the ADC to compensate for the very high output impedance of the voltage divider 

### To Do:
- [x] Find slow sampling solution
- [x] Test slow sampling system
- [ ] Make precharge command general to any analog pin, in case battery voltage divider is connected to another port.

**Comment by awickert** [comment]
Current system uses different hardware solution.
