### ISSUE TITLE
Bundle all required libraries 

### ISSUE THREAD

**Issue by bschulz1701** [NorthernWidget-Skunkworks/Margay_Library#6]
Find a way to bundle all of the required libraries with the main library for version control and ease of install 
* `DS3231_Logger.h`
* `SdFat.h`
* `MCP3421.h`

**Comment by awickert** [comment]
Two ideas.

(1) In the pre-1.0 days of Arduino, I used to have a script that pulled nightly builds of all of the core libraries, zip them, and then have another script that users could use to extract them and place them in the right location.

(2) Arduino now comes with a library manager. I have my older ALog code included as part of it. We can include all of the Margay code as well, and users will be able to easily install everything that is required using the IDE. It will still be 1 step per library, but hopefully won't be too horrible. Now, if multiple sensors become involved, we might want to create a different method for handling them ...

**Comment by awickert** [comment]
Resolved using https://github.com/NorthernWidget/Firmware-Aggregator, which generates and updates the files in https://github.com/NorthernWidget/NorthernWidget-libraries.

The only issue is when a certain library out of our control is updated in a way that breaks compatibility, such as is currently happening with SdFat. I suppose we can either allow these to remain static, deal with them on a case-by-case basis, or write some testing scripts to see if compilation succeeds.
